### ISSUE TITLE
Swift 2.0 and XCODE 7 / minimumOSVersion

### ISSUE THREAD

**Issue by notiles** [itsbonczek/kingpin#106]
@stanislaw I resolved all other problem, and I'am able to build archive and launch the upload to app store, but it failed due to the minimumOSVersion.

Could you change the info.plist by updating the minimumOSVersion to 8.0 ? 

Thanks a lot.

N.

**Comment by stanislaw** [comment]
Will do in 30 minutes.

**Comment by stanislaw** [comment]
@notiles please try https://github.com/itsbonczek/kingpin/tree/deployment-target-8.0.

**Comment by notiles** [comment]
Thanks @stanislaw, no more OS Version alert but ...

![kingpinerror](https://cloud.githubusercontent.com/assets/2833559/10075638/05f99b44-62d7-11e5-89e9-7441f862a7eb.jpg)

**Comment by stanislaw** [comment]
WOW! I'll take a look at it today. I'll also create some fake app to test submission to iTunes Connect myself.

BTW be sure read new piece of documentation I created yesterday: https://github.com/itsbonczek/kingpin/blob/master/Documentation/Framework.md. One error about unsupported architectures may be addressed here.

**Comment by notiles** [comment]
Hey @stanislaw, I was already running Kennett's script, because I was confronting this issue before, and now it doesn't fix anymore the Unsupported Architechture error.

You have to know that before, when I was using Kingpin with bitcode disable, on XCode 6 with swift 1.2 the build was succesfully posted on iTunes connect.

Also, with the master branch if I disable bitcode on my project, I only get one warning "iTunes Store operation succeeded with a warning" and after 24h I finally get my preversion on iTunes connect (It was unusually long that's why I concidered there was a bug due to bitcode disabled).

I hope that you will find a solution.

Thanks for your help!

**Comment by notiles** [comment]
Just to be sure, I downgrade KingPin to the commit 10dfaca5876169ef800e04e5a16873735bad02f1, and disable bitcode. All error messages disappear just keep a warning "iTunes Store operation succeeded with a warning" about API files usage.

**Comment by notiles** [comment]
Hello @stanislaw did you succeed to reproduce errors? Let me know if I can help you to resolve those bug.

**Comment by stanislaw** [comment]
@notiles, I have not tried submitting test application yet but tried to google all the errors that are present in your screenshot - no luck so far:

1) First of all I tried to disable bitcode and rebuilt framework but no flag `PIE` appeared as [QA 1788](https://developer.apple.com/library/ios/qa/qa1788/_index.html) recommends.

2) Also I didn't find anything meaningful for `LC_ENCRYPTION_INFO` flag -- most of the "solutions" recommend upgrading to the latest version of Xcode which does not make any sense since I have latest Xcode 7.

I'll be able to test kingpin more within two following days. Meanwhile if that is urgent you could do some experiments by [building kingpin yourself](https://github.com/itsbonczek/kingpin/blob/master/Documentation/Framework.md#how-to-build-framework-on-your-own).

I am eager to resolve this issue just don't know how to do it so far :disappointed:

**Comment by notiles** [comment]
Ok ! Thanks a lot for your help, actually I build my app with bitcode disabled and an old version of Kingpin, and it work, as I don't expect to publish my app to store until April 2016, it's not really urgent but I would like to keep a clean build during my development.

It will be comfortable to know that I'm not alone with this problem and that it's not due to other dependencies... So if you have a bit of free time, could you try to archive a project with bitcode enabled and Kingpin usage with swift 2.0 and try to validate the build ?

Thanks again!

**Comment by stanislaw** [comment]
Yes, I'll try to do submission on my own and see how it works (within 2 days).

**Comment by stanislaw** [comment]
@notiles I was able to reproduce your errors (screenshot above) so I can confirm that it is problem on kingpin side. I need to investigate it further. I'll keep you updated.

**Comment by stanislaw** [comment]
@notiles looks like I have resolved this issue:

First of all your original errors were caused by `x86_64, i386` that were not being stripped off. When I enabled that Kennett's script for Example-iOS and I used to reproduce this issue -- those errors disappeared.

But then Application Loader started displaying another error:

```
ERROR ITMS-90207: "Invalid Bundle. The bundle at 'Example-iOS.app/Frameworks/kingpin.framework' does not contain a bundle executable."
```

Inspired by [this](http://stackoverflow.com/questions/25759561/error-itms-9000-invalid-bundle-the-bundle-at-xyz-app-doesn-not-contain-bundle) I enabled flag `"Build Active Architecture Only" (ONLY_ACTIVE_ARCH)` to `YES` for Release configuration and all the errors disappeared.

I suggest you:

1) Double-check that you really strip off the debugging slices: `x86_64` and `i386` when you archive your application. You can do this by locating `kingpin.framework/kingpin` inside your built application archive and doing `lipo -info kingpin` on it -- you SHOULD NOT see there `x86_64` and `i386`. This will ensure that you really put correct architecture slices to App Store.

2) Set `"Build Active Architecture Only" (ONLY_ACTIVE_ARCH)` to `YES` for your release configuration.

See how it works and let me know about the results.

**Comment by notiles** [comment]
Great News, as I am off Tomorrow I Will test your solution next week ! Thanks a lot for your help and your job, keep in touch.

**Comment by notiles** [comment]
Hey Stanislas,  

I get the last master version of Kingpin and with "Build Active Architecture Only" (ONLY_ACTIVE_ARCH) to YES, all error disappear !

Thanks a lot!

You can closed this issue !

**Comment by stanislaw** [comment]
:+1:
