### ISSUE TITLE
NaN at some values

### ISSUE THREAD

**Issue by ppamorim** [itsbonczek/kingpin#107]
Hi.
I\`m studying this library, yesterday this library works fine. But today stops working I don`t know what happens. Then, returns this:

![captura de tela 2015-09-25 as 16 48 38](https://cloud.githubusercontent.com/assets/5521682/10110709/4cf0290e-63a5-11e5-8106-948b13912a4b.png)

My annotation is equals of the TestAnnotation, the complete source of  the MapViewController is there: https://gist.github.com/ppamorim/5c6e8d1800a4c7b5a99f

EDIT:

This happens with I use the method setAnnotations. This happens with PureLayout, I used the wrong way to create the view (with bounds) and works fine.

![captura de tela 2015-09-25 as 18 35 18](https://cloud.githubusercontent.com/assets/5521682/10112742/3bda1882-63b4-11e5-9ccf-613c4c1db6e8.png)

**Comment by stanislaw** [comment]
@ppamorim, thanks for reporting this.

It is good that you mentioned PureLayout as it can be related to some unusual frame sizes.

Could you set a break point or just NSLog to the beginning of that function `MKMapRectNormalizeToCellSize` so that I could see what is your input of both `MKMapRect mapRect` and `MKMapSize cellSize` variables? This will allow me to resolve this issue as soon as possible.

**Comment by ppamorim** [comment]
![captura de tela 2015-09-26 as 20 31 28](https://cloud.githubusercontent.com/assets/5521682/10120367/c1b55e10-648d-11e5-9c28-a6a192a6ceae.png)
![captura de tela 2015-09-26 as 20 31 58](https://cloud.githubusercontent.com/assets/5521682/10120369/c21c2686-648d-11e5-89be-47955bad8cd6.png)
![captura de tela 2015-09-26 as 20 32 14](https://cloud.githubusercontent.com/assets/5521682/10120368/c201c566-648d-11e5-9f03-d3b0041a79d6.png)

If you want I can share the source code with you.

**Comment by stanislaw** [comment]
That makes a lot of sense. You're trying to run clustering on map of MKMapRect: `{.x = -1, y = -1, width = 0, height = 0}` so that this issue pretty much reminds me another one: [iOS 7.1 64-bit crash KPTreeController #40](https://github.com/itsbonczek/kingpin/issues/40).

There I just decided to drop out from clustering procedure if one tries to cluster map of size MKMapSizeZero as it does not make any sense. Actually that is strange that you're able to enter clustering algorithm as you should probably also have map of size MKMapSizeZero.

To verify this put breakpoint on [this line](https://github.com/itsbonczek/kingpin/blob/18cb81634e7471943f3b6eaf55f09372f8d5c6ea/kingpin/KPClusteringController.m#L116) -- we want to know what exactly your map view's size is at the moment when clustering starts.

**Comment by ppamorim** [comment]
![captura de tela 2015-09-27 as 12 44 19](https://cloud.githubusercontent.com/assets/5521682/10123647/804ff8f8-6515-11e5-8bfd-8e32b44d4f89.png)

**Comment by stanislaw** [comment]
Please do the same but this time expand `_mapView` I need to look at it's dimensions.

**Comment by stanislaw** [comment]
Or if expansion will not reveal `mapRect` please do it manually like `po self.mapView.mapRect`.

**Comment by ppamorim** [comment]
@stanislaw The log is too big, I`m lost :s

**Comment by stanislaw** [comment]
I mean we just want to know what is map view's `visibleMapRect` is when you are at https://github.com/itsbonczek/kingpin/blob/18cb81634e7471943f3b6eaf55f09372f8d5c6ea/kingpin/KPClusteringController.m#L116.

**Comment by ppamorim** [comment]
@stanislaw, do you want this?
![captura de tela 2015-09-28 as 09 45 10](https://cloud.githubusercontent.com/assets/5521682/10135601/b081e92c-65c5-11e5-8d3e-1a337cc9ee95.png)

**Comment by ppamorim** [comment]
I searched about width and height of the element.
![captura de tela 2015-09-28 as 09 48 18](https://cloud.githubusercontent.com/assets/5521682/10135674/4703d9d2-65c6-11e5-9c69-b3c6116030d8.png)
![captura de tela 2015-09-28 as 09 48 28](https://cloud.githubusercontent.com/assets/5521682/10135673/47024c5c-65c6-11e5-8700-137f6054e898.png)

**Comment by stanislaw** [comment]
Yes and no :)

The break point is correct but I want you to do `po self.mapView.visibleMapRect` on it. Please do :)

**Comment by ppamorim** [comment]
@stanislaw I`ll do it on my public repository named Fun-With-Swift, then, you can test, of course.

**Comment by stanislaw** [comment]
Yes that will work. Is that repository already has what I can test or you're going to push something on top of it?

**Comment by ppamorim** [comment]
not ready yet. I`ll push something soon.

**Comment by ppamorim** [comment]
@stanislaw Done!
https://github.com/ppamorim/Fun-with-Swift
Clone it and have fun!

**Comment by stanislaw** [comment]
@ppamorim thank you for crafting that test application as it helped me to resolve this issue very quickly.

Your issue is sort of edge case: since you're using PureLayout you should be careful with the exact moment when you're trying to start clustering controller:

currently in your application you call `clusteringController.setAnnotations(annotations())` which triggers clustering on your mapView which has zero map rect at that moment.

I have pushed `0.3.1` to CocoaPods -- in this new version kingpin just drops out of clustering if a map is zero, so you should add another call to clusteringController: `clusteringController.refresh(true)` where you would be sure that your map is set to real non-zero dimensions you expect it to have (somewhere later in View Controller lifecycle like: `viewWillAppear` or `viewDidLayoutSubviews`.

P.S. For me as a developer your report gives valuable feedback about weakness of this part of kingpin's public API -- eventually next versions of kingpin will not have `setAnnotations:` method triggering clustering algorithm under the hood i.e. procedure of setting annotations (and building annotation tree for it) and clustering procedure will be called separately to prevent issues like that.

Let me know if this works for you.

**Comment by ppamorim** [comment]
I think that the initilizer needs to be invocated with the UIView lifecycle. What do you think about it?

**Comment by ppamorim** [comment]
@stanislaw Solved!
But I noticed another bizarre bug:
![captura de tela 2015-10-01 as 22 57 54](https://cloud.githubusercontent.com/assets/5521682/10238891/ea2f48c6-689b-11e5-8182-b50ce381f1ac.png)

Happens when I click in the cluster or pin. Look like the frame of the map is moving.

**Comment by stanislaw** [comment]
I am afraid this is not related to kingpin but rather to some magic that is behind PureLayout or just auto-layout in general.

The only thing kinpin does [here](https://github.com/ppamorim/Fun-with-Swift/blob/7e4db02266eb7c2d66e6a8bdb5006a7727946de6/Fun%20With%20Swift/KingPinBugController.swift#L109) is that it sets map region i.e. it does not contain any code that would affect mapView's frame size/origin.

Try investigating the auto-layout details of your implementation.
