### ISSUE TITLE
Get rid of the grid effect

### ISSUE THREAD

**Issue by SebC99** [itsbonczek/kingpin#115]
Hello,
Great work!
Do you think it could be possible to implement a 2-d tree based on principal component analysis, like described here:
http://applidium.com/en/news/too_many_pins_on_your_map/
(and here: https://github.com/applidium/ADClusterMapView/blob/master/ADClusterMapView/ADMapCluster.m)
I'm not good enough in C to do it myself... 
Any help would be appreciated!
Thanks

**Comment by stanislaw** [comment]
What's your dataset? I used kingpin for two different datasets representing real city places and both times clusters didn't look as grid.

Of course if you have a LOT of data points (like 50000) and they are distributed evenly you will see grid because that's the key weakness of grid clustering algorithm.

It would be good if you made a screenshot demonstrating your grid effect and share details of your dataset.

To answer your question: there are numerous options and this principal component analysis is only one of them (the other option is to use better tree like R-tree based with corresponding algorithms behind it). Unfortunately we do not develop kingpin actively as it works quite well as general purpose iOS library so it is unlikely that we'll start that implementation of principal component analysis.
