### ISSUE TITLE
add custom calloutview

### ISSUE THREAD

**Issue by itanchik** [itsbonczek/kingpin#68]
Can I add custom calloutview?
Thanks

**Comment by mgiraldo** [comment]
hi

I haven't been able to create a custom callout for non-clustered pins... I create my annotations like so:

```Objective-C
	KPAnnotation *annotation = [[KPAnnotation alloc] init];
	annotation.coordinate = CLLocationCoordinate2DMake(coordinate.latitude, coordinate.longitude);
	annotation.title = [NSString stringWithFormat:@"my custom title"];
	annotation.subtitle = [NSString stringWithFormat:@"my custom subtitle"];
	[m_annotationArray addObject:annotation];
```

then add this array to the cluster:

```Objective-C
	[self.clusteringController setAnnotations:m_annotationArray];
```

and it doesn't work... I always get "1 things" as the title of the callout.

what am I doing wrong?

**Comment by stanislaw** [comment]
@mgiraldo, summoned by your tweet I apoligize for delay with the answer.

Your annotations are always clustered: even if you have one annotation there is a cluster with that annotation so that title and subtitles of your single annotations are not read.

If you want to access your annotation@title - do that from: `- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id<MKAnnotation>)annotation` where you should use `kingpinAnnotation.isCluster` check. Then and here I am quoting README doc: 

> You can gain access to the cluster's annotations via -[KPAnnotation annotations].

I.e. in case of cluster with one annotation you use `(YourAnnotation *)annotations.firstObject` and obtain title from it so that it can be set to as title of your annotation view.

I hope this is enough for you to proceed with.

**Comment by mgiraldo** [comment]
Thanks!

It was a bit more involved since I had to customize `- (void)clusteringController:(KPClusteringController *)clusteringController configureAnnotationForDisplay:(KPAnnotation *)annotation` and also `NSSet` does not respond to `firstObject` so I am going with `anyObject`

Thanks a lot!

**Comment by stanislaw** [comment]
Ok, good!! Sorry about firstObject misconfusion, of course it is anyObject that is to be used with NSSet.
