### ISSUE TITLE
cluster distance threshold

### ISSUE THREAD

**Issue by mgiraldo** [itsbonczek/kingpin#76]
My annotation dataset has points that may be very close (a few meters apart). I have been playing with different values for `gridSize` and `annotationSize` and I cannot find the right values so that clusters always properly "explode". Either I have to manually zoom in by pinching until the cluster explodes or the pins do appear but on top of each other. Sometimes the cluster won't explode even at the highest zoom level.

Any ideas?

**Comment by stanislaw** [comment]
@mgiraldo, good suggestion. I need to think about it. I think I can do this during next weekend. 

Meanwhile I am all ears to hear your ideas.

My take on this is to use dynamic gridSize that would be calculated on each zoom gesture. The formula would be pretty easy: just calculate gridSize using distance threshold so that if gridSize appears to be lower than threshold it is adjusted.

P.S. Recently there were a few other suggestions that were to be added to kingpin feature set. They require major or minor redesign of kingpin code. I need to think about all this with @itsbonczek. Because it is easy to implement this threshold feature but it is not to make it fit into existing design without growing number of patches/design-hacks that will complicate kingpin's structure/design.

**Comment by mgiraldo** [comment]
@stanislaw well I'm not a CS expert so I can't really comment on algorithms... I did use this [other clustering plugin](http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html) in [some other web project](http://buildinginspector.nypl.org/)... not sure what algorithm they use but it is [open source](https://github.com/Leaflet/Leaflet.markercluster). when you arrive at an area with overlapping annotations they get shown like so:
![screenshot](http://i.imgur.com/76CSDDA.jpg)

that would be cool

the mapbox guys also have an [iOS mapping sdk](https://www.mapbox.com/mapbox-ios-sdk/) that handles clustering and is also [open source](https://github.com/mapbox/mapbox-ios-sdk) so maybe there are ideas there?

**Comment by itsbonczek** [comment]
Interesting suggestion, @mgiraldo. I think the issue lies more with how MapKit handles very close annotations rather than how kingpin does clustering. It sounds like MapKit does not support a zoom level that will provide sufficient distance between your annotations. The proposed solution would fix this, but it would be a substantial amount of effort. Unfortunately, I don't see us supporting it any time soon. 

Pull requests welcome, though, if you are feeling inspired! :smile:

**Comment by mgiraldo** [comment]
I understand although I'd like to note that the overlapping pins are not so much the problem as is the fact that the cluster does not explode at all. I am left with the cluster annotation and no red pins in the highest zoom level

**Comment by stanislaw** [comment]
@mgiraldo, as promised, I'll look at what can be done tomorrow. I will most likely suggest you separate branch with some workaround on top and suggest you to try it. Please wait.

**Comment by mgiraldo** [comment]
thanks!

:)

**Comment by mgiraldo** [comment]
after a lot of trial and error I found these values in the clustering algorithm that work most of the time (all clusters usually explode):
```Objective-C
	algorithm.gridSize = CGSizeMake(5, 5);
	algorithm.annotationSize = CGSizeMake(50, 50);
```
not sure if this helps in any way

best

**Comment by stanislaw** [comment]
@mgiraldo, let's start with something very simple:

Find category for MKMapView which provides you with zoom level ([one example](https://github.com/johndpope/MKMapViewZoom)).

Then implement clustering controller's delegate method:

```objective-c
- (BOOL)clusteringControllerShouldClusterAnnotations:(KPClusteringController *)clusteringController {
    return self.mapView.zoomLevel < 14; // Find zoom level that suits your dataset
}
```

Let me know if that works for you.

**Comment by itsbonczek** [comment]
@mgiraldo - Apologies for my misunderstanding, I fully understand the issue now. @stanislaw's approach is a good one for this particular situation (and one that I've successfully used in the past).

**Comment by mgiraldo** [comment]
that seems to work. thanks!
