### ISSUE TITLE
Add Swift-based tester target

### ISSUE THREAD

**Issue by itsbonczek** [itsbonczek/kingpin#80]
It would be good to gain an understanding for how Swift-based apps interface with kingpin. Would be good to have Swift documentation as well...

**Comment by stanislaw** [comment]
Bryan,

I've just added initial `tester-swift` target - it is already in master branch. I am very new to Swift so there might be some imperfection in coding style and implementation details but looks like it is now working the same way as `tester` app works.

Key notes:

1) Bridging beetween Swift with Objective-C turned out to be a really simple thing: presence of `tester-swift-Bridging-Header.h` header and in Swift target's options corresponding `Objective-C Bridging Header` option pointing to that .h file - they make tester-swift app to be aware of kingpin's code so no imports are needed anywhere else.

2) I have not added "Reset" button and "Animations" toggle yet. But that's easy to add.

3) I am not sure if my Swift code is good enough to be quoted in Swift part of documentation and I am not sure how/where to write that Swift part of documentation.

Let me know what you think.

**Comment by stanislaw** [comment]
This ticket can also be closed if all is fine.

**Comment by stanislaw** [comment]
Or maybe now it is time to extend Documentation folder with usage docs for both Objective-C and Swift versions. Bryan, what do you think?

**Comment by stanislaw** [comment]
I have just written basic instructions for Swift: [Basic usage (Swift)](https://github.com/itsbonczek/kingpin/blob/master/Documentation/Documentation.md#basic-usage-swift).

**Comment by itsbonczek** [comment]
:+1:
