### ISSUE TITLE
Best place to detect collapse / expand ?

### ISSUE THREAD

**Issue by linked67** [itsbonczek/kingpin#84]
Hi,

I have a custom MKAnnotationView with a NSTimer that refresh a picture on it. There is no need to run all these timers on the same time and i want to start/stop it when clustered or not.

What is the best place to do this ?
Maybe in:

    - (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id<MKAnnotation>)annotation
or

    - (void)clusteringController:(KPClusteringController *)clusteringController configureAnnotationForDisplay:(KPAnnotation *)annotation 

Or in other place ?

**Comment by itsbonczek** [comment]
I think you'd want to use -viewForAnnotation in this case, since that's what gets called before the annotation is displayed. The tricky thing will be stopping the timer when the MKAnnotationView goes off screen (gets put into the reuse queue) as I don't think there is an easy way to know when that happens. Good luck!
